### ISSUE TITLE
Installation faild

### ISSUE THREAD

**Issue by prodperso** [Thunder7yoshi/AltStore-Beta#1]
hello; 

i don"t know man but it keeps giving me this error i tryed everything
SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status. WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CA SSL invalid CA

can you help please.

**Comment by Thunder7yoshi** [comment]
DM me on discord Thunder7#9020
