### ISSUE TITLE
could not find altserver....

### ISSUE THREAD

**Issue by zooloo01** [Thunder7yoshi/AltStore-Beta#10]
Every time I try to load an ipa or apple id it says: could not find altserver
(I've tried it more than once)
And itunes and the icloud working with the official altstore just doesn't support iOS 14 so it's not a problem with / icloud / itunes

**Comment by Thunder7yoshi** [comment]
Re-install

**Comment by zooloo01** [comment]
> Re-install

I've tried many times ....
