### ISSUE TITLE
How do you get Delta Beta? (free?)

### ISSUE THREAD

**Issue by Aqee1** [Thunder7yoshi/AltStore-Beta#14]
Is there a way to get Delta Beta for free? In the screenshots you show it has the Beta version but I only get the normal one, I want to try DS games through Delta. It's fine if there isn't a way to get it.

**Comment by Assfugil** [comment]
https://apps.altstore.io you can find the offical link here.

**Comment by Aqee1** [comment]
Thanks! :)
