### ISSUE TITLE
Please add macos version

### ISSUE THREAD

**Issue by atomizasser** [Thunder7yoshi/AltStore-Beta#2]

**Comment by Thunder7yoshi** [comment]
Added! [ https://github.com/Thunder7yoshi/AltStore-Beta/releases/tag/v1.3b3-1.3b3 ]

**Comment by Thunder7yoshi** [comment]
Added! click [Here](https://github.com/Thunder7yoshi/AltStore-Beta/releases/tag/v1.3b3-1.3b3)

**Comment by rmvz3** [comment]
I'd like a Mac version too but I can't find any mac release. Have you removed Mac support?
