### ISSUE TITLE
Apple Tv 4k not showing

### ISSUE THREAD

**Issue by francescofact** [Thunder7yoshi/AltStore-Beta#20]
Hi, i know that this is not an officiale repo, but anyone knows, why i don't have the menu "sideload ipa" and in the devices list there is not my apple tv 4k (same network)

**Comment by Catta1997** [comment]
Prova a connetterla tramite Xcode
Riporto la guida ufficiale:
```
- Navigate to Settings>Remotes and Devices>Remote App and Devices on your ATV4.
- Go to your mac and use Xcode's Window menu >Devices and Simulators..you should see your ATV4 in the Discovered list on the left.
- Click on the Apple TV Icon in Devices panel... it will ask you for a Pairing Code that is displayed on the ATV4.
- Enter the code and Xcode should begin pairing with the ATV4.
```

**Comment by francescofact** [comment]
Done, but one paired, on the apple tv my mac appear in the list, but xcode doesn't find it anymore and AltStore keep saying "No devices"
