### ISSUE TITLE
fake

### ISSUE THREAD

**Issue by iop34** [Thunder7yoshi/AltStore-Beta#21]
it says when you check for updates for altserver its version is 1.5.0.1 but when altstore is sideloaded to your phone/iPad it says altstore 1.4.2 which is the latest pubic release

**Comment by francescofact** [comment]
You have to sideload also the beta ipa file...

**Comment by Thunder7yoshi** [comment]
As freancescofact said you will have to do an extra step in order to get it done properly. You can join the discord to find the guide to it.
