### ISSUE TITLE
Is there any ways to sideload more than 3 apps?

### ISSUE THREAD

**Issue by RoastedGoose** [Thunder7yoshi/AltStore-Beta#4]
for example if there are 2 altstores login with 2 free accounts...

**Comment by Bhavinjain260** [comment]
Is it POSSIBLE to install 2 altstore in one device?

**Comment by RoastedGoose** [comment]
> Is it POSSIBLE to install 2 altstore in one device?

yes but useless. i think it's no difference than switching between 2 free accounts in one altsore.
