### ISSUE TITLE
Latest AltServer beta that is only available at discord

### ISSUE THREAD

**Issue by Assfugil** [Thunder7yoshi/AltStore-Beta#6]
I managed to get altstore alpha by adding https://alpha.altstore.io but the altstore alpha in it requires lastest altserver beta only available in discord.

Will you update it?

**Comment by Thunder7yoshi** [comment]
Since this is called AltServer Beta and not Alpha, I won't update it with any Alphas

**Comment by Assfugil** [comment]
Well AltStore alpha requires latest altserver **beta**.

That AltServer is a beta.

**Comment by Thunder7yoshi** [comment]
AltStore Alpha works with AltServer Stable and Beta.

You just add the source to AltStore and install AltStore Alpha

**Comment by Assfugil** [comment]
Deactivating apps does not work with the latest public altserver beta in altstore alpha.
“AltServer does not support this request”

**Comment by Thunder7yoshi** [comment]
Let’s discuss about that on discord
