### ISSUE TITLE
DLL error on 1.4.0.1 using windows 8.1

### ISSUE THREAD

**Issue by jboothuk** [Thunder7yoshi/AltStore-Beta#9]
The procedure entry point IsWowprocess2 could not be located in the dynamic link library 

This is version 1.4.0.1

**Comment by Thunder7yoshi** [comment]
AltServer only supports windows 10

**Comment by jboothuk** [comment]
Well the non beta version works a treat

**Comment by jboothuk** [comment]
Issue resolved, edited hex code
